### ISSUE TITLE
How to process nested pointer for arena.New

### ISSUE THREAD

**Issue by someview** [huandu/go-clone#19]
How to use arena to allocte memory for Outer,should we use arena to allocate memory for the nested field Inner?
Is there some method to identify  the memory-allocated way.
```
type Outer struct {
   *Inner
}
type Inner Struct {
}
```
a arena object can not be used concurrently.Is there some example for arena pool

**Comment by huandu** [comment]
> How to use arena to allocate memory...
In this package, if you're using an arena to clone a struct, all newly allocated memory spaces are allocated from the arena.

Here is a sample to clone a value with arena.

```go
ar := arena.NewArena()

// The cloned is a deep copy of v and allocated from ar.
cloned := clone.ArenaClone(ar, v)
```

> Is there any way to identify whether an instance is allocated from an arena...
I don't think we have any formal way to do so. There is a very tricky way to check whether a pointer is in an arena, though not recommended. That is, we can call `np := arena.Clone(p)` to get a new pointer and then check `np == p`. If it's true, p is allocated from heap (a.k.a. not from arena), otherwise, it's allocated from an arena. However, even if we know `p` is allocated from an arena, we still don't know which arena holds the `p`.

// An arena object cannot be used concurrently...
AFAIK, arena APIs can be used in concurrent environment. You can share an arena instance in different goroutines and use it concurrently. So you don't need to have an arena pool.

**Comment by someview** [comment]
> > How to use arena to allocate memory...
> 
> In this package, if you're using an arena to clone a struct, all newly allocated memory spaces are allocated from the arena.
> 
> Here is a sample to clone a value with arena.
> 
> ```go
> ar := arena.NewArena()
> 
> // The cloned is a deep copy of v and allocated from ar.
> cloned := clone.ArenaClone(ar, v)
> ```
> 
> > Is there any way to identify whether an instance is allocated from an arena...
> 
> I don't think we have any formal way to do so. There is a very tricky way to check whether a pointer is in an arena, though not recommended. That is, we can call `np := arena.Clone(p)` to get a new pointer and then check `np == p`. If it's true, p is allocated from heap (a.k.a. not from arena), otherwise, it's allocated from an arena. However, even if we know `p` is allocated from an arena, we still don't know which arena holds the `p`.
> 
> > An arena object cannot be used concurrently...
> 
> AFAIK, arena APIs can be used in concurrent environment. You can share an arena instance in different goroutines and use it concurrently. So you don't need to have an arena pool.

I'm going to use arena  and  CAS2 to improve  [lock free hash map](https://github.com/cornelk/hashmap.git)
```
type Dict[K compareable, V any] struct {...}
```
But the V may be like this：
```
type Outer struct {
   *Inner
    slice []int
}
type Inner Struct {
}
```
So, I would create this like this：
```
ar := arena.NewArena()
outer := arena.New[Outer](ar)
outer.Inner = arena.New[Inner](ar)
...
```
This seems relatively more steps to create V. The hashmap may use kvpair wrapper to store v. To reduce allcote memory op and gc, a way is using object pool that is built in arena memory. We can allocate all memory the map needs and establish a mechanism for reusing objects like kvpairs  in arena or in a series of arena.Now there seems no use cases for object pools that is built with arena.

**Comment by huandu** [comment]
Here is a tip for you to make allocation code much simpler.

```go
// Declare a global variable as a template.
var valueTemplate = &Outer{
    Inner: &Inner{
        // initialize more fields...
    },
    slice: []int{},
}

// You will have a newly cloned value allocated from ar.
v := clone.ArenaClone(ar, valueTemplate)
```
