### ISSUE TITLE
List clone incorrect

### ISSUE THREAD

**Issue by xukun311** [huandu/go-clone#3]
hello, I find a bug below:
          l := list.New()
	 l.PushBack("123")

	for i := l.Front(); i != nil; i = i.Next() {
		fmt.Println(i.Value)
	}

	newl := clone.Slowly(l).(*list.List)
	for i := newl.Front(); i != nil; i = i.Next() {
		fmt.Println(i.Value)
	}

output like this:
123
123
<nil>
why cloned new object  contain a <nil>?
Is it the wrong way to use it？

**Comment by huandu** [comment]
It's a bug.

**Comment by huandu** [comment]
The bug is triggered by the field `root` in `list.List`.

```go
type List struct {
    root Element
    len  int
}
```

When a list is not empty, front elem's prev and back elem's next point to the address of `root`. These two pointers are cycle pointers. `Slowly` fully depends on the visited map to set cycle pointers to right value. Unfortunately, as the type of `root` is `Element` rather than `*Element`, the address of `root` is not added to the visited map.

**Comment by huandu** [comment]
The fix 130985a resolves this issue by adding all struct fields which may contain cycle pointers to the visited map. This fix will make `Slowly` slightly slower.

**Comment by xukun311** [comment]
hello， when i use ordermap ,i find the same question

 // import orderedmap "github.com/wk8/go-ordered-map"

om := orderedmap.New()

	om.Set("foo", "bar")
	
	// iterating pairs from oldest to newest:
	for pair := om.Oldest(); pair != nil; pair = pair.Next() {
		fmt.Printf("%s => %s\n", pair.Key, pair.Value)
	}

	newOM := clone.Slowly(om).(*orderedmap.OrderedMap)
	for pair := newOM.Oldest(); pair != nil; pair = pair.Next() {
		fmt.Printf("%s => %s\n", pair.Key, pair.Value)
	}
